### PR TITLE
MAINT: Add PyOpenGL on macOS

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@marsipu I think since we by default try PyOpenGL on macOS and raise an error if it's not there, it should be in the recipe for that platform. WDYT?

It would have fixed https://github.com/mne-tools/mne-python/runs/5364484062?check_suite_focus=true

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin please rerender

**Review by hoechenberger — CHANGES_REQUESTED** [review]
@larsoner Since the package is not `noarch` anymore, you should add a `skip` entry to the `build` section to constrain the Python version, see https://conda-forge.org/docs/maintainer/adding_pkgs.html#build

Afterwards you'll need to re-render agaun

**Comment by larsoner** [comment]
It looks like it only built 3.7+ anyway, presumably because the `mne` dep is 3.7+. Do you think we should have it anyway?

**Comment by hoechenberger** [comment]
> It looks like it only built 3.7+ anyway, presumably because the `mne` dep is 3.7+. Do you think we should have it anyway?

Yes please add it; maybe rules have changed but I remember that not having such a constraint would regularly lead to a rejection of my PRs from `conda-forge/staged-recipes`; not sure why the linter doesn't pick up on it though! I'd add it just to be sure…

**Comment by hoechenberger** [comment]
> presumably because the `mne` dep is 3.7+.

btw `conda-forge` (currently) doesn't build with anything older than 3.7. Still, I think it's good practice to explicitly add the constraint!

**Comment by larsoner** [comment]
@conda-forge-admin please rerender

**Comment by larsoner** [comment]
Feel free to merge if you're happy @hoechenberger

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thank you, @larsoner

**Pull request merged**
