### PR TITLE
Bump to 0.1.7

### PR DESCRIPTION
**Pull request by marsipu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by hoechenberger** [comment]
No need to do that, @marsipu – we've set up a bot that automatically bumps version numbers and updates hashes as it detects a new release on PyPI. Of course you'll still have to update dependencies manually, if necessary, though.

**Comment by larsoner** [comment]
You can see the bot did its business already, too:

https://github.com/conda-forge/mne-qt-browser-feedstock/pull/2

**Comment by hoechenberger** [comment]
> You can see the bot did its business already, too:

Hah! I missed that one :)

**Comment by marsipu** [comment]
Thanks good to know. So I close this one, right?

**Pull request closed without merging**
